# Generated by Django 3.2.18 on 2023-02-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sdk_doc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
