# Generated by Django 3.2.18 on 2023-02-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_sdk_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='index',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='prizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
